// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorgueManager.Infrastructure.Data;

#nullable disable

namespace MorgueManager.Infrastructure.Migrations
{
    [DbContext(typeof(MorgueDbContext))]
    [Migration("20251208140149_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MorgueManager.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2175),
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "Admin@123",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.Corpse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentPaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeathTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HealthTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceptionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.HasIndex("StorageId");

                    b.ToTable("Corpses");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.PersonalBelonging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorpseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorpseId");

                    b.ToTable("PersonalBelongings");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2321),
                            IsDeleted = false,
                            LocationCode = "A-01",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2324),
                            IsDeleted = false,
                            LocationCode = "A-02",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2327),
                            IsDeleted = false,
                            LocationCode = "A-03",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2329),
                            IsDeleted = false,
                            LocationCode = "A-04",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2331),
                            IsDeleted = false,
                            LocationCode = "A-05",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2333),
                            IsDeleted = false,
                            LocationCode = "A-06",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2335),
                            IsDeleted = false,
                            LocationCode = "A-07",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2341),
                            IsDeleted = false,
                            LocationCode = "A-08",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2343),
                            IsDeleted = false,
                            LocationCode = "A-09",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2354),
                            IsDeleted = false,
                            LocationCode = "A-10",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2358),
                            IsDeleted = false,
                            LocationCode = "B-01",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2361),
                            IsDeleted = false,
                            LocationCode = "B-02",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2362),
                            IsDeleted = false,
                            LocationCode = "B-03",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2364),
                            IsDeleted = false,
                            LocationCode = "B-04",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2366),
                            IsDeleted = false,
                            LocationCode = "B-05",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2367),
                            IsDeleted = false,
                            LocationCode = "B-06",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2368),
                            IsDeleted = false,
                            LocationCode = "B-07",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2371),
                            IsDeleted = false,
                            LocationCode = "B-08",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2372),
                            IsDeleted = false,
                            LocationCode = "B-09",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2374),
                            IsDeleted = false,
                            LocationCode = "B-10",
                            RowVersion = new byte[0],
                            State = 0,
                            Zone = 1
                        });
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2250),
                            Description = "Giá lưu kho mỗi ngày (VND)",
                            IsDeleted = false,
                            Key = "PricePerDay",
                            Value = "500000"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 21, 1, 47, 995, DateTimeKind.Local).AddTicks(2252),
                            Description = "Cảnh báo lưu lâu quá (ngày)",
                            IsDeleted = false,
                            Key = "WarningThreshold",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.Corpse", b =>
                {
                    b.HasOne("MorgueManager.Core.Entities.Storage", "Storage")
                        .WithMany("Corpses")
                        .HasForeignKey("StorageId");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("MorgueManager.Core.Entities.Storage", "Storage")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.PersonalBelonging", b =>
                {
                    b.HasOne("MorgueManager.Core.Entities.Corpse", "Corpse")
                        .WithMany("PersonalBelongings")
                        .HasForeignKey("CorpseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpse");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.Corpse", b =>
                {
                    b.Navigation("PersonalBelongings");
                });

            modelBuilder.Entity("MorgueManager.Core.Entities.Storage", b =>
                {
                    b.Navigation("Corpses");

                    b.Navigation("MaintenanceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
